# app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app-container
          image: my-app:latest  # Your app's container image
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "my-db-service"  # The name of the DB service
            - name: DB_PORT
              value: "3306"  # Default MySQL port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
