# db-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-db-service
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None  # Headless service to allow internal communication
