# db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  db_username: dXNlcm5hbWU=  # "username" in base64
  db_password: cGFzc3dvcmQ=  # "password" in base64
